# Configuration for the cfp_data_analysis project

scheduler: greedy
 
entsoe_download:
  start_date: "20241230" # format as YYYYMMDD
  end_date: "20241231"
  rebuild: false # not implemented, use --rerun-triggers inputs params to avoid re-downloading
 
entsoe_integration:
  start_date: "20230101"
  end_date: "20241231"

nem_download:
  start_date: "20230101" # format as YYYYMMDD
  end_date: "20230131"
  nemosis_cache_dir: "data/nemosis_cache"
  rebuild: false

data_types: ["prices", "load_forecast", "load_actual", "vre", "generation", "crossborder"]
