name: lcox-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - anyio=4.6.2=py312hca03da5_0
  - appnope=0.1.4=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py312h80987f9_1
  - arrow=1.3.0=py312hca03da5_0
  - arrow-cpp=13.0.0=hce30654_49_cpu
  - asttokens=2.4.1=pyhd8ed1ab_0
  - async-lru=2.0.4=py312hca03da5_0
  - attrs=24.3.0=py312hca03da5_0
  - aws-c-auth=0.7.22=h8a62e84_10
  - aws-c-cal=0.7.1=h94d0942_1
  - aws-c-common=0.9.23=h99b78c6_0
  - aws-c-compression=0.2.18=h94d0942_7
  - aws-c-event-stream=0.4.2=hb74cd8f_15
  - aws-c-http=0.8.2=had1507a_6
  - aws-c-io=0.14.10=hcdb10ff_1
  - aws-c-mqtt=0.10.4=h856d8ab_8
  - aws-c-s3=0.6.0=ha9fd6de_2
  - aws-c-sdkutils=0.1.16=h94d0942_3
  - aws-checksums=0.1.18=h94d0942_7
  - aws-crt-cpp=0.27.3=h9d3339c_2
  - aws-sdk-cpp=1.11.329=he6360a2_9
  - babel=2.14.0=pyhd8ed1ab_0
  - beautifulsoup4=4.12.3=py312hca03da5_0
  - blas=2.101=netlib
  - blas-devel=3.9.0=1_netlib
  - bleach=6.2.0=py312hca03da5_0
  - blosc=1.21.6=h5499902_0
  - bokeh=3.6.0=py312hca03da5_0
  - boost-cpp=1.85.0=h103c1d6_4
  - bottleneck=1.4.2=py312ha86b861_0
  - brotli=1.1.0=hb547adb_1
  - brotli-bin=1.1.0=hb547adb_1
  - brotli-python=1.1.0=py312h9f69965_1
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.4=h5505292_0
  - c-blosc2=2.15.2=h069cb6c_0
  - ca-certificates=2024.11.26=hca03da5_0
  - cached-property=1.5.2=py_0
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2024.12.14=py312hca03da5_0
  - cffi=1.17.1=py312h3eb5a62_1
  - colorama=0.4.6=py312hca03da5_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.3.1=py312h48ca7d4_0
  - country_converter=1.2=pyhd8ed1ab_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - debugpy=1.8.11=py312h313beb8_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=py312hca03da5_0
  - exceptiongroup=1.2.0=py312hca03da5_0
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.6.4=h313beb8_0
  - fonttools=4.53.0=py312h7e5086c_0
  - forallpeople=2.6.7=pyhd8ed1ab_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.12.1=hadb7bae_2
  - gflags=2.2.2=h313beb8_1
  - glog=0.7.1=heb240a5_0
  - gmp=6.3.0=hebf3989_1
  - gmpy2=2.1.5=py312h524cf62_3
  - h11=0.14.0=py312hca03da5_0
  - h2=4.1.0=pyhd8ed1ab_0
  - h5py=3.12.1=nompi_py312h34530d4_103
  - hdf5=1.14.4=nompi_ha698983_103
  - hpack=4.0.0=py_0
  - httpcore=1.0.5=pyhd8ed1ab_0
  - httpx=0.27.0=py312hca03da5_0
  - hyperframe=6.0.1=pyhd3eb1b0_0
  - icu=75.1=hfee45f7_0
  - importlib-metadata=8.5.0=py312hca03da5_0
  - importlib_metadata=8.5.0=hd3eb1b0_0
  - importlib_resources=6.4.0=py312hca03da5_0
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - ipykernel=6.29.5=py312hca03da5_0
  - ipython=8.30.0=py312hca03da5_0
  - ipywidgets=8.1.5=py312hca03da5_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=py312hca03da5_0
  - jinja2=3.1.4=py312hca03da5_1
  - joblib=1.4.2=py312hca03da5_0
  - json5=0.9.25=py312hca03da5_0
  - jsonpointer=3.0.0=py312h81bd7bf_0
  - jsonschema=4.23.0=py312hca03da5_0
  - jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_1
  - jupyter=1.1.1=pyhd8ed1ab_1
  - jupyter-lsp=2.2.5=pyhd8ed1ab_0
  - jupyter_client=8.6.2=pyhd8ed1ab_0
  - jupyter_console=6.6.3=py312hca03da5_1
  - jupyter_core=5.7.2=py312hca03da5_0
  - jupyter_events=0.10.0=py312hca03da5_0
  - jupyter_server=2.14.1=py312hca03da5_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_0
  - jupyterlab=4.2.5=py312hca03da5_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_1
  - jupyterlab_server=2.27.3=py312hca03da5_0
  - jupyterlab_widgets=3.0.13=py312hca03da5_0
  - kaleido-core=0.2.1=h80987f9_0
  - kiwisolver=1.4.5=py312h389731b_1
  - krb5=1.21.3=hf3e1bf2_0
  - lcms2=2.16=ha0e7c42_0
  - lerc=4.0.0=h313beb8_0
  - libabseil=20240116.2=cxx17_h313beb8_0
  - libaec=1.1.3=h313beb8_0
  - libarrow=13.0.0=h4d6bf39_49_cpu
  - libblas=3.9.0=1_h9886b1c_netlib
  - libboost=1.85.0=hf763ba5_4
  - libboost-devel=1.85.0=hf450f58_4
  - libboost-headers=1.85.0=hce30654_4
  - libbrotlicommon=1.1.0=hb547adb_1
  - libbrotlidec=1.1.0=hb547adb_1
  - libbrotlienc=1.1.0=hb547adb_1
  - libcblas=3.9.0=1_h9886b1c_netlib
  - libcrc32c=1.1.2=hc377ac9_0
  - libcurl=8.10.1=h13a7ad3_0
  - libcxx=19.1.6=ha82da77_1
  - libdeflate=1.23=hec38601_0
  - libedit=3.1.20230828=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libevent=2.1.12=h02f6b3c_1
  - libexpat=2.6.4=h286801f_0
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=13_2_0_hd922786_3
  - libgfortran5=13.2.0=hf226fd6_3
  - libgoogle-cloud=2.26.0=hfe08963_0
  - libgoogle-cloud-storage=2.26.0=h1466eeb_0
  - libgrpc=1.62.2=h9c18a4f_0
  - libiconv=1.17=h0d3ecfb_2
  - libjpeg-turbo=3.0.3=h80987f9_0
  - liblapack=3.9.0=1_h9886b1c_netlib
  - liblapacke=3.9.0=1_h9886b1c_netlib
  - libllvm14=14.0.6=hd1a9a77_4
  - libnghttp2=1.64.0=h6d7220d_0
  - libopenblas=0.3.27=openmp_h6c19121_0
  - libpng=1.6.44=hc14010f_0
  - libprotobuf=4.25.3=hc39d83c_1
  - libre2-11=2023.09.01=h7b2c953_2
  - libsodium=1.0.18=h1a28f6b_0
  - libsqlite=3.45.2=h091b4b1_0
  - libssh2=1.11.0=h7a5bd25_0
  - libthrift=0.19.0=h026a170_1
  - libtiff=4.7.0=h551f018_3
  - libtmglib=3.9.0=1_h9886b1c_netlib
  - libutf8proc=2.8.0=h1a8c8d9_0
  - libwebp-base=1.4.0=h93a5062_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.13.5=h178c5d8_1
  - libxslt=1.1.41=hf4d3faa_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=18.1.7=hde57baf_0
  - llvmlite=0.43.0=py312h313beb8_0
  - lxml=5.3.0=py312h1d4350b_0
  - lz4-c=1.9.4=h313beb8_1
  - markupsafe=2.1.5=py312he37b823_0
  - mathjax=2.7.5=hca03da5_0
  - matplotlib=3.9.2=py312hca03da5_1
  - matplotlib-base=3.9.2=py312h7ef442a_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mistune=3.0.2=pyhd8ed1ab_0
  - mpc=1.3.1=h91ba8db_0
  - mpfr=4.2.1=h41d338b_1
  - mpmath=1.3.0=py312hca03da5_0
  - munkres=1.1.4=py_0
  - nbclient=0.10.0=pyhd8ed1ab_0
  - nbconvert=7.16.4=py312hca03da5_0
  - nbconvert-core=7.16.4=pyhd8ed1ab_0
  - nbconvert-pandoc=7.16.4=hd8ed1ab_0
  - nbformat=5.10.4=py312hca03da5_0
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.6.0=py312hca03da5_0
  - notebook=7.2.2=py312hca03da5_1
  - notebook-shim=0.2.4=pyhd8ed1ab_0
  - numba=0.60.0=py312hd77ebd4_0
  - numexpr=2.10.1=py312h5d9532f_0
  - openssl=3.3.2=h8359307_0
  - orc=2.0.1=h47ade37_1
  - overrides=7.7.0=pyhd8ed1ab_0
  - packaging=24.2=py312hca03da5_0
  - pandas=2.2.3=py312hcf29cfe_0
  - pandoc=3.2=hce30654_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.4=py312hca03da5_0
  - patsy=0.5.6=py312hca03da5_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=11.0.0=py312haf37ca6_0
  - pip=24.2=py312hca03da5_0
  - pkgutil-resolve-name=1.3.10=py312hca03da5_1
  - platformdirs=4.2.2=pyhd8ed1ab_0
  - plotly=5.24.1=py312h989b03a_0
  - pluggy=1.5.0=py312hca03da5_0
  - prometheus_client=0.21.0=py312hca03da5_0
  - prompt-toolkit=3.0.47=pyha770c72_0
  - prompt_toolkit=3.0.47=hd8ed1ab_0
  - psutil=5.9.8=py312he37b823_0
  - pthread-stubs=0.4=h27ca646_1001
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py-cpuinfo=9.0.0=py312hca03da5_0
  - pycountry=24.6.1=pyhd8ed1ab_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyobjc-core=10.3.1=py312hbb55c70_0
  - pyobjc-framework-cocoa=10.3.1=py312hbb55c70_0
  - pyparsing=3.2.0=py312hca03da5_0
  - pysocks=1.7.1=py312hca03da5_0
  - pytables=3.10.2=py312h4b6ede8_0
  - pytest=8.2.2=pyhd8ed1ab_0
  - python=3.12.2=hdf0ec26_0_cpython
  - python-dateutil=2.9.0post0=py312hca03da5_2
  - python-dotenv
  - python-fastjsonschema=2.20.0=py312hca03da5_0
  - python-json-logger=3.2.1=py312hca03da5_0
  - python-kaleido=0.2.1=py312hca03da5_0
  - python_abi=3.12=5_cp312
  - pyyaml=6.0.2=py312h80987f9_0
  - pyzmq=26.2.0=py312h313beb8_0
  - qtconsole-base=5.6.1=pyha770c72_1
  - qtpy=2.4.1=py312hca03da5_0
  - re2=2023.09.01=h4cba328_2
  - readline=8.2=h1a28f6b_0
  - referencing=0.35.1=pyhd8ed1ab_0
  - requests=2.32.3=py312hca03da5_1
  - rfc3339-validator=0.1.4=py312hca03da5_0
  - rfc3986-validator=0.1.1=py312hca03da5_0
  - rpds-py=0.18.1=py312h552d48e_0
  - scikit-learn=1.5.2=py312h313beb8_0
  - scipy=1.15.0=py312hb7ffdcd_0
  - seaborn=0.13.2=py312hca03da5_0
  - seaborn-base=0.13.2=pyhd8ed1ab_0
  - send2trash=1.8.3=pyh31c8845_0
  - setuptools=75.1.0=py312hca03da5_0
  - snappy=1.2.1=h313beb8_0
  - sniffio=1.3.1=pyhd8ed1ab_0
  - sqlite=3.45.2=hf2abe2d_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.4=py312h80987f9_0
  - sympy=1.13.3=py312hca03da5_0
  - tbb=2021.8.0=h48ca7d4_0
  - tenacity=9.0.0=py312hca03da5_0
  - terminado=0.18.1=pyh31c8845_0
  - threadpoolctl=3.5.0=py312h989b03a_0
  - tinycss2=1.3.0=pyhd8ed1ab_0
  - tk=8.6.13=h5083fa2_1
  - tomli=2.0.1=py312hca03da5_1
  - tornado=6.4.2=py312h80987f9_0
  - traitlets=5.14.3=py312hca03da5_0
  - types-python-dateutil=2.9.0.20241206=pyhd8ed1ab_0
  - typing-extensions=4.12.2=py312hca03da5_0
  - typing_extensions=4.12.2=py312hca03da5_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=py312hca03da5_2
  - websocket-client=1.8.0=py312hca03da5_0
  - wheel=0.44.0=py312hca03da5_0
  - widgetsnbextension=4.0.13=py312hca03da5_0
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - xyzservices=2024.6.0=pyhd8ed1ab_0
  - xz=5.4.6=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - zeromq=4.3.5=h313beb8_0
  - zipp=3.21.0=py312hca03da5_0
  - zlib=1.3.1=h8359307_2
  - zlib-ng=2.2.3=h13dfb9a_0
  - zstd=1.5.6=hb46c0d2_0
  - snakemake
  - pulp
  - pip:
      - charset-normalizer==3.4.1
      - entsoe-py==0.6.16
      - idna==3.10
      - numpy==2.2.1
      - pyarrow==18.1.0
      - pytz==2024.2
      - six==1.17.0
      - soupsieve==2.6
      - tzdata==2024.2
      - urllib3==2.3.0
prefix: /Users/peter/anaconda3/envs/fca_env