name: lcox-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pandas
  - pyarrow
  - numpy
  - openpyxl
  - entsoe-py
  - country_converter
  - python-dotenv
  - plotly
  - jupyter

  - pip:
    - nemosis
    - snakemake